config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "main#show"

  resources :maintenance_checks, only: [:show]
  resources :inspection_items, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :inspection_items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/inspection_check.rb
class InspectionCheck < ApplicationRecord

  include ActionView::Helpers::NumberHelper

  belongs_to :inspection_item
  has_one :category, through: :inspection_item

  validates :mileage_in_km, presence: true

  enum :todo, [:inspection, :replacement]
  enum :interval_style, [:fixed, :recurring]
  enum :condition, [:normal, :severe, :normal_and_severe]

  def should_check_for_mileage?(mileage)
    mileage_in_float = mileage.to_f

    return false if mileage_in_float.zero?

    if recurring?
      mileage_quotient = mileage_in_float / mileage_in_km.to_f
      return true if mileage_quotient.to_f == mileage_quotient.to_i
    end

    mileage_in_float == mileage_in_km
  end

  def to_s
    "#{todo.capitalize} #{recurring? ? 'every' : 'once'} #{number_to_currency(mileage_in_km, unit: "", precision: 0)} kms #{"(#{notes.downcase})" if notes.present?}"
  end

end

app/models/inspection_item.rb
class InspectionItem < ApplicationRecord

  has_many :inspection_checks, dependent: :destroy
  belongs_to :category

  validates :name, presence: true

  def to_param
    [id, name.parameterize].join("-")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/inspection_items_controller.rb
class InspectionItemsController < ApplicationController

  def index
    @inspection_items = InspectionItem.where("name LIKE '%#{params[:part]}%'")
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def show
  end

end

app/controllers/maintenance_checks_controller.rb
class MaintenanceChecksController < ApplicationController

  def show
    @mileage_in_km = params[:id]
    @condition = params[:driving_condition].to_s.presence || "normal"
    @inspection_checks = Mechanic.ask(@mileage_in_km, condition: @condition)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inspection_items/index.html.erb
<section>
  <span class="block mb-2 font-semibold"> Your search of '<%= params[:part] %>' yielded <%= pluralize(@inspection_items.count, "result") %>: </span>

  <section class="mb-4 grid grid-cols-2 gap-2">
    <% @inspection_items.each do |inspection_item| %>
      <%= link_to inspection_items_path(part: inspection_item.name), class: "cursor-pointer border-l-4 border border-yellow-300 bg-white" do %>
        <div class="p-1"> <%= inspection_item.name %> </div>
      <% end %>
    <% end %>
  </section>

  <% if @inspection_items.count == 1 %>
    <% inspection_item = @inspection_items.first %>

    <% normal_checks = inspection_item.inspection_checks.normal %>
    <% severe_checks = inspection_item.inspection_checks.severe %>
    <% both_checks = inspection_item.inspection_checks.normal_and_severe %>

    <section class="mb-4">
      <div class="bg-white p-2">
        <span class="text-lg font-semibold block mb-4"> <%= inspection_item.name %> </span>

        <div class="mb-4">
          <span class="font-semibold block mb-1"> For normal driving </span>
          <% Array(normal_checks + both_checks).sort_by { |c| c.mileage_in_km }.each do |check| %>
            <div> ⚙️  <%= check.to_s %> </div>
          <% end %>
        </div>

        <div>
          <span class="font-semibold block mb-1"> For severe driving </span>
          <% Array(severe_checks + both_checks).sort_by { |c| c.mileage_in_km }.each do |check| %>
            <div> ⚙️  <%= check.to_s %> </div>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>

  <%= link_to "↩️", root_path, class: "block text-xl text-center bg-white cursor-pointer px-4 py-2 border border-gray-400" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "JB74 Maintenance" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 barlow-condensed-regular">
    <main class="flex flex-col h-screen justify-between">
      <section class="mb-auto lg:flex lg:h-screen lg:items-center lg:justify-center">
        <div class="p-4 w-full md:w-3/4">
          <%= link_to root_path, class: "block mb-2 text-4xl text-center" do %>
            Maintain Your Jimny JB74 🇵🇭 
          <% end %>

          <span class="block mb-2 text-lg text-center bg-yellow-300"> based on the official jimny owner's manual 2021. </span>

          <div class="flex justify-center">
            <%= render "shared/jimny_svg", color: "text-yellow-700" %>
            <%= render "shared/jimny_svg", color: "text-gray-700" %>
            <%= render "shared/jimny_svg", color: "text-blue-800" %>
          </div>

          <%= yield %>
        </div>
      </section>

      <footer class="flex justify-center p-4"> 
        <span class="text-gray-400"> © 2024. 🇵🇭 </span>
      </footer>
    </main>
  </body>
</html>

app/views/main/show.html.erb
<section>
  <div>
    <%= form_with url: inspection_items_path, method: :get do |f| %>
      <%= f.text_field :part, class: "border-l-4 border-yellow-300 p-2 shadow-md h-12 text-lg w-full", placeholder: "🔎 Search car part (e.g. coolant, bearing, engine oil)" %>
    <% end %>
  </div>

  <div class="flex justify-center w-full">
    <span class="text-xl"> ... </span>
  </div>

  <div>
    <label class="font-semibold block mb-1"> 👉🏼  Or search by maintenance schedule: </label>
    <div class="grid grid-cols-3 lg:grid-cols-5 gap-2">
      <%= link_to "1,000 kms", maintenance_check_path(1_000, driving_condition: :severe), class: "border-l-4 border-yellow-300 p-2 text-lg text-black bg-white shadow-md hover:bg-yellow-300" %>

      <% ((5_000..150_000).step(5_000)).each do |mileage_in_km| %>
        <%= link_to "#{number_to_currency(mileage_in_km, unit: "", precision: 0)} kms", maintenance_check_path(mileage_in_km, driving_condition: :severe), class: "p-2 text-lg text-black bg-white shadow-md hover:bg-yellow-300" %>
      <% end %>
    </div>
  </div>
</section>

app/views/maintenance_checks/show.html.erb
<section>
  <span class="block p-1 bg-black text-white text-2xl text-center mb-4"> 
    <%= pluralize(number_to_currency(@mileage_in_km, unit: "", precision: 0), "km") %> 
  </span>

  <div class="bg-yellow-300 p-1 mb-4">
    <span class="text-md"> 💡 To get a detailed maintenance schedule, click the corresponding part item. </span>
  </div>

  <div class="flex">
    <%= link_to "normal driving", maintenance_check_path(@mileage_in_km, driving_condition: :normal), class: "text-lg px-2 py-1 border #{'bg-white text-black' if @condition == "normal"}" %>
    <%= link_to "severe driving", maintenance_check_path(@mileage_in_km, driving_condition: :severe), class: "text-lg px-2 py-1 border #{'bg-white text-black' if @condition == "severe"}" %>
  </div>

  <section class="bg-white border shadow-md p-2 overflow-y-auto h-80 mb-4">
    <% if @inspection_checks.empty? %>
      <div class="text-center text-lg"> 
        No checks found for <%= number_to_currency(@mileage_in_km, unit: "", precision: 0) %>kms. 
      </div>
    <% else %>
      <span class="text-md italic block font-normal mb-2"> 
        * 
        <span class="font-semibold"><%= pluralize(@inspection_checks.replacement.size, "item") %> for replacement</span>, and 
        <span class="font-semibold"><%= pluralize(@inspection_checks.inspection.size, "item") %> for inspection</span>.
      </span>

      <div class="grid grid-cols-1 gap-0">
        <% @inspection_checks.each do |inspection_check| %>
          <div class="flex items-center cursor-pointer"> 
            <span class="block mr-2"> 
              <% if inspection_check.inspection? %>
                <span class="text-sm p-1 bg-gray-500 text-white"> inspect </span>
              <% else %>
                <span class="text-sm p-1 bg-red-600 text-white"> replace </span>
              <% end %>
            </span>

            <%= link_to inspection_items_path(part: inspection_check.inspection_item.name) do %>
              <div class="w-full hover:bg-yellow-300 hover:underline">
                <span class="text-lg"> <%= inspection_check.inspection_item.name %> </span>
                <% if inspection_check.notes.present? %>
                  <span class="bg-yellow-300"> <%= inspection_check.notes.downcase %> </span>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>

  <%= link_to "↩️", root_path, class: "block text-xl text-center bg-white cursor-pointer px-4 py-2 border border-gray-400" %>
</section>